<a href="https://colab.research.google.com/github/ThexG02/Python-For-ML/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


Basics of the Arrays in Numpy

In [6]:
arr= np.array([1,2,3,4,"hello"])
arr

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [5]:
list_L =[1,2,3,4,"hello"]
list_L

[1, 2, 3, 4, 'hello']

In [9]:
l=[[1,2],[3,4],[5,6]]
larray=np.array(l)
larray

array([[1, 2],
       [3, 4],
       [5, 6]])

Array Generation


range funtion in numpy : arange(start,end)

In [10]:
la = np.arange(1,10)
la

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Zeroes for matrix generation


In [12]:
lm = np.zeros((4,8))
lm

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
lm = np.ones((3,4))
lm

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Linear space : linspace funtion - return evenly spaced numbers over a spercified Interval

In [15]:
lla= np.linspace(0,5,10)
lla

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Random genertaion function

In [3]:
la = np.random.rand(5)
la

array([0.94434847, 0.05813134, 0.21817182, 0.15919775, 0.90936227])

In [4]:
la= np.random.randn(10)
la

array([ 1.31278798, -1.1514061 , -0.06324725,  0.2574462 ,  0.95840444,
       -0.67843413, -0.0424464 , -0.04236611,  1.18958463,  0.16481306])

In [5]:
la=np.random.randint(1,100,10)
la

array([35, 73, 25,  5, 37, 36, 57, 54, 67, 56])